spring.application.name=Biblioteca Personal

server.port=8071

spring.datasource.url=jdbc:postgresql://localhost:5432/bibliotecadb
spring.datasource.username=postgres
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false